### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4096x320 and 768x320)

### ISSUE THREAD

**Issue by CJohnDesign** [d8ahazard/sd_dreambooth_extension#826] opened 2023-01-23 05:35 UTC
First off, just wanna say I see all the commits you're pushing - thank you!

## Issue
I'm running Colab and not seeing these version numbers spit out into the console. All I could find was the python version:

`
Python: Python 3.8.10
`

**Describe the bug**

I get an error as training is about to begin

**Log:**

```
Initializing dreambooth training...
Pre-processing pro100% 30/30 [00:00<00:00, 138.09it/s]
Concept requires 0 class images per instance image.
Sorting instance images100% 1/1 [00:00<00:00, 28149.69it/s]
Nothing to generate.
Replace CrossAttention.forward to use xformers
Exception importing 8bit adam: No module named 'bitsandbytes'
WARNING:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:Exception importing 8bit adam: No module named 'bitsandbytes'
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 292, in inner_loop
    import bitsandbytes as bnb
ModuleNotFoundError: No module named 'bitsandbytes'
Found 0 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (Without Caching)
Bucket 0 (512, 512, 0) - Instance Images: 30 | Class Images: 0 | Max Examples/batch: 30
Total Buckets 1 - Instance Images: 30 | Class Images: 0 | Max Examples/batch: 30
Processing images...100% 30/30 [00:00<00:00, 2273.75it/s]
Total images / batch: 30, total examples: 30
Processing images...100% 30/30 [00:00<00:00, 2254.32it/s]
Total dataset length (steps): 30
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 30
  Num Epochs = 100
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 75
  Total optimization steps = 3000
  Total training steps = 3000
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Adam: False, Prec: fp16
  Gradient Checkpointing: False
  EMA: False
  UNET: True
  LR: 2e-06
  V2: False
Steps:   0% 0/3000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 455, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 984, in main
    return inner_loop()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 121, in decorator
    return function(batch_size, grad_size, prof, log_file, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 859, in inner_loop
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_condition.py", line 481, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_blocks.py", line 789, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/attention.py", line 301, in forward
    attn_output = self.attn2(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 296, in forward_xformers
    k_in = self.to_k(context_k)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 170, in lora_Linear_forward
    return lora_forward(self, input, torch.nn.Linear_forward_before_lora(self, input))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4096x320 and 768x320)
Steps:   0% 0/3000 [00:00<?, ?it/s]
Restored system models.
```

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS?
Google Colab

What GPU are you using?
Standard

db_config.json:
```
{
    "adamw_weight_decay": 0.01,
    "attention": "xformers",
    "cache_latents": false,
    "center_crop": false,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/dreambooth/TSL/classifiers_0",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "class_negative_prompt": "",
            "class_prompt": "drawing for business",
            "class_token": "a business drawing",
            "instance_data_dir": "/content/gdrive/MyDrive/_TRAIN/TSL/pro",
            "instance_prompt": "ohwx drawing ",
            "instance_token": "ohwx drawing",
            "is_valid": true,
            "n_save_sample": 1,
            "num_class_images": 0,
            "num_class_images_per": 0,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 40,
            "save_sample_negative_prompt": "",
            "save_sample_prompt": "ohwx drawing",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/concepts_list.json",
    "custom_model_name": "",
    "epoch": 0,
    "epoch_pause_frequency": 0.0,
    "epoch_pause_time": 60.0,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "gradient_set_to_none": true,
    "graph_smoothing": 50.0,
    "half_model": false,
    "has_ema": false,
    "hflip": false,
    "initial_revision": 0,
    "learning_rate": 2e-06,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0002,
    "lora_model_name": [],
    "lora_rank": 4,
    "lora_txt_learning_rate": 0.0002,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "fp16",
    "model_name": "TSL",
    "model_dir": "/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/dreambooth/TSL",
    "model_path": "/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/dreambooth/TSL",
    "num_train_epochs": 100,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/dreambooth/TSL/working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.75,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": true,
    "save_embedding_every": 10,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_preview_every": 5,
    "save_safetensors": false,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": true,
    "scheduler": "ddim",
    "shuffle_tags": true,
    "snapshot": "",
    "src": "/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.ckpt",
    "stop_text_encoder": 0.75,
    "train_batch_size": 1,
    "train_imagic": false,
    "train_unet": true,
    "use_8bit_adam": true,
    "use_concepts": true,
    "use_ema": false,
    "use_lora": false,
    "use_subdir": true,
    "v2": false
}
```

**Comment by jimlin1668478052** [comment] 2023-01-25 04:37
Yep, it is exactly the same issue I found. It is very disappointing after using a lot of resource to generate a lot of reference images and then this error bumps out.

**Comment by navarisun** [comment] 2023-02-06 21:31
same error happens today, how can this be solved ?

**Comment by xiangcp** [comment] 2023-02-07 09:24
same error happens:
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (8192x320 and 768x320)`

**Comment by xiangcp** [comment] 2023-02-07 10:06
my batch size is 2, so it`s 8192x320

**Comment by CJohnDesign** [comment] 2023-02-11 05:26
Still getting this error

**Comment by CJohnDesign** [comment] 2023-02-11 06:07
Can I offer a bounty for this one?

**Comment by xiangcp** [comment] 2023-02-13 01:04
I have adjusted the sd-webui version and the dreambooth version respectively for testing, but this error still occurs

**Comment by xiangcp** [comment] 2023-02-17 02:50
My solution to this error was to change the diffusers versions. 'pip install diffusers==0.10.2'

**Comment by CJohnDesign** [comment] 2023-02-17 03:40
> My solution to this error was to change the diffusers versions. 'pip install diffusers==0.10.2'

My man! I'm going to try this as soon as I get home! Thanks for sharing 🤘

**Comment by d8ahazard** [comment] 2023-02-17 18:31
@CJohnDesign 

I mean this in the most respectful way possible...but this is not the right solution. Heck, after we merge the latest changes in /dev to main, this will outright cause the extension to refuse to run...because it's the wrong solution.

The problem is with the version of xformers being forced by Auto1111, and the proper solution is to use the latest dev release from pypi instead of whatever junk Auto1111 is forcing.

And, for a bit of history - it's s*it like this from a base application that makes changes without proper testing and validation that is the reason I'm making my own stand-alone application to host the Dreambooth code.

Please revert your diffusers version to 0.12.1 and update xformers, and verify this fixed your issue.

**Comment by CJohnDesign** [comment] 2023-02-17 19:54
I feel your pain... and thank you for all your contributions - I see all the commits.

I tried installing the last 3 releases but still get the same error. I'm not sure if its still forcing the stable release but I ran this in the colab before starting:
```
!pip install diffusers==0.12.1
!pip install xformers==0.0.17.dev461
```

Here is the error again:
```
Initializing dreambooth training...
2023-02-17 19:50:44.135513: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2023-02-17 19:50:44.135570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 37774 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:04.0, compute capability: 8.0
Pre-processing ROSE100% 99/99 [00:01<00:00, 65.09it/s]
Concept requires 0 class images per instance image.
Sorting instance images100% 1/1 [00:00<00:00, 21620.12it/s]
Nothing to generate.
Replace CrossAttention.forward to use xformers
Found 0 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
Bucket 0 (512, 512, 0) - Instance Images: 99 | Class Images: 0 | Max Examples/batch:  99
Total Buckets 1 - Instance Images: 99 | Class Images: 0 | Max Examples/batch: 99
Caching latents...100% 99/99 [00:09<00:00, 24.46it/s]
Total images / batch: 99, total examples: 99
Caching latents...100% 99/99 [00:09<00:00, 10.88it/s]
Total dataset length (steps): 99
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 99
  Num Epochs = 100
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 50
  Total optimization steps = 9900
  Total training steps = 9900
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: None, Adam: False, Prec: fp16
  Gradient Checkpointing: False
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 2e-06
  V2: False
Steps:   0% 0/9900 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 455, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 989, in main
    return inner_loop()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 121, in decorator
    return function(batch_size, grad_size, prof, log_file, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 864, in inner_loop
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/operations.py", line 489, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_condition.py", line 481, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_blocks.py", line 789, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/attention.py", line 307, in forward
    attn_output = self.attn2(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 296, in forward_xformers
    k_in = self.to_k(context_k)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 178, in lora_Linear_forward
    return lora_forward(self, input, torch.nn.Linear_forward_before_lora(self, input))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4096x320 and 768x320)
Steps:   0% 0/9900 [00:00<?, ?it/s]
Restored system models.
```

**Comment by CJohnDesign** [comment] 2023-02-18 00:01
Here's my Colab: https://colab.research.google.com/drive/1Kntrs0lRU4zPt_kBSlr_x2mc2hM6O8a7?usp=sharing

I tried updating `launch.py` to reflect xformers 17 too. Is there anywhere else I should change it?

**Comment by xiangcp** [comment] 2023-02-18 02:20
> @CJohnDesign
> 
> I mean this in the most respectful way possible...but this is not the right solution. Heck, after we merge the latest changes in /dev to main, this will outright cause the extension to refuse to run...because it's the wrong solution.
> 
> The problem is with the version of xformers being forced by Auto1111, and the proper solution is to use the latest dev release from pypi instead of whatever junk Auto1111 is forcing.
> 
> And, for a bit of history - it's s*it like this from a base application that makes changes without proper testing and validation that is the reason I'm making my own stand-alone application to host the Dreambooth code.
> 
> Please revert your diffusers version to 0.12.1 and update xformers, and verify this fixed your issue.

But in your requirements.txt, the diffusers version is 0.10.2.

**Comment by CJohnDesign** [comment] 2023-02-18 03:28
I'm not seeing that - my extension's req.txt is `diffusers==0.12.1`

**Comment by mediashock** [comment] 2023-02-22 04:08
I'm using xformers: 0.0.17.dev449 in SD install and i'm getting the same error.

**Comment by ride5k** [comment] 2023-02-23 17:33
> My solution to this error was to change the diffusers versions. 'pip install diffusers==0.10.2'

this worked for me as well

**Comment by d8ahazard** [comment] 2023-03-01 03:13
This should be resolved with https://github.com/d8ahazard/sd_dreambooth_extension/releases/tag/1.0.11

Adjusting the diffusers version is no longer suggested or recommended...use what is in requirements.txt

**Closed by d8ahazard** 2023-03-01 03:13 UTC
Labels: new
