### ISSUE TITLE
Crash when at 50% of training

### ISSUE THREAD

**Issue by DomDumont** [d8ahazard/sd_dreambooth_extension#61] opened 2022-11-09 10:19 UTC
Hi,
Each time I try to train , i got an error halfway

Saving checkpoint at step 500.
Successfully trained model for a total of 500 steps, converting to ckpt.
Error completing request
...
...
...
g_cuda = torch.Generator(device=accelerator.device).manual_seed(args.seed)
AttributeError: 'DreamboothConfig' object has no attribute 'seed'

**Comment by Luke2642** [comment] 2022-11-09 10:35
did you do a search for open issues? There's a fix for this.

**Comment by DomDumont** [comment] 2022-11-09 10:44
Hi, thanks for this notice. Unfortunately the fix is not so obvious, reading various comments it seems there is no official solution. Each person just try to manually add a seed somewhere but crash later ...
Maybe I need to investigate more .
Thanks for your help

**Comment by Luke2642** [comment] 2022-11-09 11:07
Sorry, I forgot I also added

"seed": 1234
to db_config.py line 108

and it works

**Comment by DomDumont** [comment] 2022-11-09 12:59
Hi,
I try your fix but end up with 
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by Luke2642** [comment] 2022-11-09 13:21
I'm on windows so I don't have that same folder structure, I only have \venv\Lib\site-packages\diffusers

Plus, I'm on python 3.10 not 3.8. Maybe try that? But honestly I have no idea.

**Comment by DomDumont** [comment] 2022-11-09 13:44
No problem.Thanks a lot for your help.
By the way, I am on Windows too, it seems the venv directory is embedded in the whole stable-diffusion-webui project , mine is located at
stable-diffusion-webui\venv\lib\site-packages\diffusers

**Comment by d8ahazard** [comment] 2022-11-09 18:03
So, the seed issue was fixed yesterday. There may still be an issue generating preview image, but it shouldn't be breaking anymore until I can find a proper resolution.

Please update to the latest version, try again, and close this issue if resolved. This will help me focus on fixing the things I've still got broken. :D

**Comment by DomDumont** [comment] 2022-11-09 18:06
Will do

**Comment by DomDumont** [comment] 2022-11-10 09:24
Hi, after upgrade to the new version, I got a new error :

    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'

**Comment by CrazyBoyM** [comment] 2022-11-10 13:21
sames there are two bug to fix:
```
AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'
```
this one is because the 'Gradient Checkpointing' option was checked in the webpage
and another bug
```
Steps:  50%|██████████████████████████████████████████                                          | 500/1000 [04:04<03:42,  2.25it/s, loss=0.0896, lr=5e-6]You have passed a non-standard module None. We cannot verify whether it has the correct type
Error completing request
Arguments: ('newModel', '/root/autodl-tmp/test3', '', '', False, True, '', '', '', 1, 7.5, 40, 0, 512, False, True, 1, 1, 1, 1000, 1, False, 5e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 500, 500, 'no', True, '', False, True, True) {}
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10.6/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 403, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_path(
  File "/root/miniconda3/envs/py3.10.6/lib/python3.10/site-packages/transformers/utils/hub.py", line 297, in cached_path
    raise EnvironmentError(f"file {url_or_filename} not found")
OSError: file /root/autodl-tmp/stable-diffusion-webui/models/dreambooth/newModel/working/safety_checker/preprocessor_config.json not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/root/autodl-tmp/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 275, in start_training
    trained_steps = main(config)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 953, in main
    save_weights(lifetime_step, save_model, save_img)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 812, in save_weights
    pipeline = StableDiffusionPipeline.from_pretrained(
  File "/root/miniconda3/envs/py3.10.6/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 383, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/root/miniconda3/envs/py3.10.6/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 308, in from_pretrained
    feature_extractor_dict, kwargs = cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/miniconda3/envs/py3.10.6/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 443, in get_feature_extractor_dict
    raise EnvironmentError(
OSError: Can't load feature extractor for '/root/autodl-tmp/stable-diffusion-webui/models/dreambooth/newModel/working/safety_checker'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/root/autodl-tmp/stable-diffusion-webui/models/dreambooth/newModel/working/safety_checker' is the correct path to a directory containing a preprocessor_config.json file

Steps:  50%|██████████████████████████████████████████                                          | 500/1000 [04:05<04:05,  2.03it/s, loss=0.0896, lr=5e-6]
```
i think it may caused by the "Save a checkpoint every N steps, 0 to disable" and "Generate a preview image every N steps, 0 to disable" option was set to 500 (just a guess)

**Comment by d8ahazard** [comment] 2022-11-10 17:40
> ```
> 
> Steps:  60%|██████████████████████████████████████████████████▋                                  | 596/1000 [04:38<03:08,  2.15it/s, loss=0.092, lr=5e-6]
> ```
> 
> it works fine when set them to other value(but also failed when step equal that value)

Can you try now? I think the issue was that diffusers weren't being updated properly - that or pytorch.

After you relaunch the webui, please paste the lines that show the diffusers/pytorch/dreambooth versions, please.

**Comment by CrazyBoyM** [comment] 2022-11-10 17:56
> > ```
> > 
> > Steps:  60%|██████████████████████████████████████████████████▋                                  | 596/1000 [04:38<03:08,  2.15it/s, loss=0.092, lr=5e-6]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it works fine when set them to other value(but also failed when step equal that value)
> 
> Can you try now? I think the issue was that diffusers weren't being updated properly - that or pytorch.
> 
> After you relaunch the webui, please paste the lines that show the diffusers/pytorch/dreambooth versions, please.

my diffusers version is 0.3.0.  
and i think it may caused by the https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements_versions.txt
everytime i start webui it will auto install packages by the requirements_version(althrough i have install diffusers0.7.2 by hand with pip install diffusers -U).

**Comment by d8ahazard** [comment] 2022-11-10 17:57
If you're using the latest version of the extension, diffusers should automatically be updated over the version in requirements_versions.txt

**Comment by CrazyBoyM** [comment] 2022-11-10 18:03
> If you're using the latest version of the extension, diffusers should automatically be updated over the version in requirements_versions.txt

I will try it tomorrow,  the time is too late(AM 02:00) for me, have to sleep.

**Closed** 2022-11-10 22:36 UTC
Labels: Possibly Resolved
