### ISSUE TITLE
Ability to patch lora without merging

### ISSUE THREAD

**Issue by esbe1175** [d8ahazard/sd_dreambooth_extension#516] opened 2022-12-13 12:41 UTC
Much like hypernetworks, a LORA can be patched in, so you dont need to create a new several gigabytes big model every time you want to run inference on a different model using a LORA. An example of that process can be seen [here](https://github.com/cloneofsimo/lora/blob/master/scripts/run_with_text_lora_also.ipynb), where the lora and text encoder lora is monkeypatched into the model, then inference is ran. If we could have a LORA selector for webui, that'd be amazing!

**Comment by Thomas-MMJ** [comment] 2022-12-13 15:48
I think this is a duplicate of #508

**Closed** 2022-12-13 16:56 UTC
