### ISSUE TITLE
Missing key(s) in state_dict:

### ISSUE THREAD

**Issue by Izumizaki** [d8ahazard/sd_dreambooth_extension#713] opened 2023-01-06 23:22 UTC
Trying to create a new model in the Dreambooth extension. Getting this error right after "Converting unet...". Any idea why this is happening? I'm using the Protogen X 5.8 model (converted from safetensors to ckpt).

```
Checkpoint S:\Games\StableDiffusion\models\Stable-diffusion\Styles\ProtogenX58.ckpt has both EMA and non-EMA weights.
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
Exception setting up output: Error(s) in loading state_dict for UNet2DConditionModel:
        Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias".
        Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight".
Traceback (most recent call last):
  File "S:\Games\StableDiffusion\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 922, in extract_checkpoint
    unet.load_state_dict(converted_unet_checkpoint)
  File "S:\Games\StableDiffusion\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias".
        Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight".
Pipeline or config is not set, unable to continue.
```

```
Python revision: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Dreambooth revision:
SD-WebUI revision:

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
```

**Comment by d8ahazard** [comment] 2023-01-07 00:24
This would be the issue here:

Exception setting up output: Error(s) in loading state_dict for UNet2DConditionModel:
        Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias".
        Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight".
        
The converted safetensors model doesn't have the proper keys for it to be able to convert a HF model to diffusion weights.

If you have the ability to convert models using "something", I'd suggest looking at the script from huggingface to convert a safetensors model directly to diffusion weights. You should be able to stick this in /models/dreambooth/your_model/working, and train on it.

I'm going to close this, as it's safetensors related, which is on my radar of stuff to implement. I just need to ensure that the basic extension works as intended first. ;)

**Closed by d8ahazard** 2023-01-07 00:24 UTC

**Comment by AI-Casanova** [comment] 2023-01-07 14:55
Workaround, merge safetensors with sd1.5 with sd1.5 as the base and alpha = 1

This creates a copy of your safetensors that can be broken down to diffusers.
