### ISSUE TITLE
[LORA] CKPT generation of the second training, generates the basic model without the training.

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [d8ahazard/sd_dreambooth_extension#553] opened 2022-12-16 11:47 UTC
`
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Dreambooth revision: c678a431b5d79ba7e1c38d7629ca7e0c79166a1f
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**
CKPT generation of the second(continued from the first training) training, generates the basic model without the training, when using LORA.
First training results when converted to ckpt, indeed contain the training results as expected. 
In the Model and Lora Model I selected the proper versions. Also I've tried without and with "Custom Model Name", same results.

**Environment**
What OS?
Ubuntu 22.04
If Windows - WSL or native?
No
What GPU are you using?
RTX 2080 8GB

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by a-l-e-x-d-s-9** [comment] 2022-12-16 11:50
@ExponentialML 
Have you noticed this problem?

**Comment by LLSean** [comment] 2022-12-16 12:35
> 

I met this problem too. Training is not processing.

**Comment by a-l-e-x-d-s-9** [comment] 2022-12-16 20:19
@LLSean 
In my case, from what I see in sample images while training, it looks like training is working the second time because they are definitely not from the base model. But when generating ckpt, it forgot all the training, probably the ckpt was just a copy of a base model, without any training.

**Comment by deepseareo** [comment] 2022-12-18 06:54
I also got the same problem, even if there is a new pt file during the second training, the ckpt cannot be generated correctly

**Comment by NaughtDZ** [comment] 2022-12-18 12:37
Me too.I try traning loong time but the result look like haven't been trained.

**Comment by a-l-e-x-d-s-9** [comment] 2022-12-18 12:54
Yeah, it is very problematic to train that way, I have to start over each time.

**Comment by dmnro123** [comment] 2022-12-19 19:59
seeing the same issue, did you figure out a workaround?

**Comment by a-l-e-x-d-s-9** [comment] 2022-12-19 20:19
There is no workaround that I am aware of. This issue limits the possibility of testing severely, and I haven't been able to produce good training with LORA for faces not even once, after many attempts. I'm getting worried that LORA is just far below the quality of a regular Dreambooth.

**Comment by Smashcolor** [comment] 2022-12-21 04:56
Can confirm it is still broken as of e033cad0691479bb844280dc2900e84454ec9a3c. 4 hours of training today only to get an unaltered base model when I generate a checkpoint.

**Comment by Nyaster** [comment] 2022-12-28 12:20
Same in me

**Comment by Begin19** [comment] 2022-12-29 09:42
seems like this function is not applying CLIPAttention module: 

```
def weight_apply_lora(
    model, loras, target_replace_module=None, alpha=1.0
):
    if target_replace_module is None:
        target_replace_module = ["CrossAttention", "Attention"]
```
try to add "CLIPAttention" in list here

**Comment by Begin19** [comment] 2022-12-29 09:50
extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py:334

chage to this:
 
weight_apply_lora(loaded_pipeline.text_encoder, torch.load(lora_txt), alpha=lora_txt_alpha, target_replace_module=["CLIPAttention"])

**Comment by Begin19** [comment] 2022-12-29 10:50
seems like LORA is broken here, while training it produce some results, but when merging to model all results is disappeared

**Comment by a-l-e-x-d-s-9** [comment] 2022-12-29 18:57
@Begin19 
Were you able to get any good results from the training with Lora?

**Comment by Begin19** [comment] 2022-12-30 06:31
> @Begin19 Were you able to get any good results from the training with Lora?

only while training phase
preview images generating while training is pretty good but when I hit Generate checkpoint and try to use it in txt2img routine I get nothing (worse subject quality)

**Comment by Begin19** [comment] 2022-12-30 06:35
I think the problem is in merging LORA with the model, because while training it works fine (I see it from samples generation)

**Comment by Begin19** [comment] 2022-12-30 06:53
maybe @Thomas-MMJ have some thoughts

**Comment by Thomas-MMJ** [comment] 2022-12-30 22:28
I'd try deleting and reinstalling the extension, I was experiencing bugs for awhile till I did that.

**Comment by d8ahazard** [comment] 2023-01-01 16:04
Should be fixed in the latest release:

https://github.com/d8ahazard/sd_dreambooth_extension/commit/15244fef18c35864be6f6c2e1c0237dadc5415c1

**Closed by d8ahazard** 2023-01-01 16:04 UTC
Labels: new
