### ISSUE TITLE
help! genrate class images problem

### ISSUE THREAD

**Issue by figurehunt** [d8ahazard/sd_dreambooth_extension#1003] opened 2023-03-03 02:14 UTC
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash:3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision: d4e2f7d5dc5c67cc6292c8b8137b688a43247c35
SD-WebUI revision: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39
Diffusers version is 0.13.1 
Torch version is 1.13.1+cu117
Torch vision version is 0.14.1+cu117
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)? yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI? yes

**Have you updated Dreambooth to the latest revision?yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
yes, i have restart the SD for several times, but still can't slove the problem.
**Describe the bug**

i follow the tutorials to fill the blank of the board. but when i click to generate some class images, it shows:

Exception training model: 'join() argument must be str, bytes, or os.PathLike object, not 'list''.

it shows, when I simply click TRAIN. 
I have restart the software, even the computer. the problem happen always.
I am a new comer and I need your help! thanks very much!
(A clear and concise description of what the bug is)

**Provide logs**

To create a public link, set `share=True` in `launch()`.
Model dir set to: C:\AI\models\dreambooth\liaoyuanhuo-V1
Wizard results:<br>Num Epochs: 150<br>Num instance images per class image: 5
Model dir set to: C:\AI\models\dreambooth\liaoyuanhuo-V1
Model dir set to: C:\AI\models\dreambooth\liaoyuanhuo-V1
Model dir set to: C:\AI\models\dreambooth\liaoyuanhuo-V1
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.13.1. Performing monkey-patch...

We need a total of 160 class images.
Generating 160 class images for training...

Using scheduler: DEISMultistep
Got scheduler: <class 'diffusers.schedulers.scheduling_deis_multistep.DEISMultistepScheduler'>
  File "C:\AI\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 555, in start_training
    result = main(use_txt2img=use_txt2img)
  File "C:\AI\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1133, in main
    return inner_loop()
  File "C:\AI\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\AI\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 198, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(args, use_txt2img=use_txt2img,
  File "C:\AI\extensions\sd_dreambooth_extension\dreambooth\utils\gen_utils.py", line 134, in generate_classifiers
    builder = ImageBuilder(
  File "C:\AI\extensions\sd_dreambooth_extension\helpers\image_builder.py", line 126, in __init__
    lora_model_path = os.path.join(shared.models_path, "lora", lora_model)
  File "ntpath.py", line 143, in join
  File "genericpath.py", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

log as above

**Environment**

What OS?
WIN10
If Windows - WSL or native?
i guess is native? it is just a normal computer for work. i am not a coder.TT
What GPU are you using?
N 4090
**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json
![1](https://user-images.githubusercontent.com/126839246/222614120-7e463a93-a3be-484a-9e3e-7f6dedf21ab0.png)
![2](https://user-images.githubusercontent.com/126839246/222614134-9c4df6ba-1a0f-48c2-8316-af592b99060b.png)
![3](https://user-images.githubusercontent.com/126839246/222614137-9e686f1f-7d2a-4e42-bd2d-861b4522645e.png)

thank you so much!

**Comment by logging-synchronous** [comment] 2023-03-03 02:21
I've been running into this as well. I just hit "Generate Class Images" or "Train" again and it works.

**Comment by figurehunt** [comment] 2023-03-03 02:45
> I've been running into this as well. I just hit "Generate Class Images" or "Train" again and it works.

well, i try it again. I still won't work. 
I make it back to all the ext version back to around 11/2, and i fill the same stuff and click, it tells: Exception training model: 'module 'diffusers' has no attribute 'DEISMultistepScheduler''.

so it is a diffusers problem?

**Comment by ArrowM** [comment] 2023-03-03 03:47
The issue is your Lora model name in the dbconfig. It's a list (`[]`) change it to a normal string.

**Comment by ArrowM** [comment] 2023-03-03 03:56
> > I've been running into this as well. I just hit "Generate Class Images" or "Train" again and it works.
> 
> well, i try it again. I still won't work. I make it back to all the ext version back to around 11/2, and i fill the same stuff and click, it tells: Exception training model: 'module 'diffusers' has no attribute 'DEISMultistepScheduler''.
> 
> so it is a diffusers problem?

you are using an old version of the diffusers library.

**Comment by ArrowM** [comment] 2023-03-03 22:49
> TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'

should be fixed by #1005

**Closed by ArrowM** 2023-03-03 22:49 UTC
Labels: new
