### ISSUE TITLE
Error when creating a model from a safetensor model

### ISSUE THREAD

**Issue by patrickas** [d8ahazard/sd_dreambooth_extension#418] opened 2022-12-05 10:32 UTC
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]   
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b                                     
Installing requirements for Web UI                                                        
Checking Dreambooth requirements...                                                       
Checking/upgrading existing torch/torchvision installation                                
Checking torch and torchvision versions                                                   
Dreambooth revision is c2fc683ebcf4db23cfce22626aa6a7b565994c96                           
[+] bitsandbytes version 0.35.0 installed.                                                
[ ] diffusers version 0.9.0 installed.                                                    
[+] transformers version 4.21.0 installed.                                                
[+] torch version 1.12.1+cu116 installed.                                                 
[+] torchvision version 0.13.1+cu116 installed.                                           
[ ] xformers version 0.0.14.dev0 installed.                                               

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

I have recently converted all my models to safetensors (and deleted most of the originals to save space)
When I go to the "Create Model" tab and select a "Source Checkpoint" that is a .safetensor converted check point the model cannot be created and I get errors.
(Using an original .ckpt file works fine)

**Provide logs**

Extracting checkpoint...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/2.2GB
 Reserved: 0.0/2.2GB

Exception with the conversion: invalid load key, '\xfd'.
Traceback (most recent call last):
  File "C:\Programs\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 860, in extract_checkpoint
    checkpoint = torch.load(checkpoint_info[0], map_location=map_location)["state_dict"]
  File "C:\Programs\stable-diffusion-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, *args, **kwargs)
  File "C:\Programs\stable-diffusion-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Programs\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Programs\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xfd'.
Error completing request
Arguments: ('vansieSD15', '1_StableDIffusion\\v1-5-pruned-emaonly.safetensors [21c7ab71]', 'euler-ancestral', 'runwayml/stable-diffusion-v1-5', '', False) {}
Traceback (most recent call last):
  File "C:\Programs\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 860, in extract_checkpoint
    checkpoint = torch.load(checkpoint_info[0], map_location=map_location)["state_dict"]
  File "C:\Programs\stable-diffusion-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, *args, **kwargs)
  File "C:\Programs\stable-diffusion-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Programs\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Programs\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xfd'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\Programs\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\Programs\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 968, in extract_checkpoint
    del pipe
UnboundLocalError: local variable 'pipe' referenced before assignment

Traceback (most recent call last):
  File "C:\Programs\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\Programs\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Programs\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

**Environment**

What OS?
Windoes

If Windows - WSL or native?
Native

What GPU are you using?
Nvidia GeForce RTX 2060 12 GB VRam

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by d8ahazard** [comment] 2022-12-06 04:31
Safetensors is presently not supported. Heck, it's barely even in the official diffusers repo right now.

But, it's on my radar, and will be implemented in the future.

**Comment by jsbach-jung** [comment] 2022-12-28 06:16
Wanted to let you all know about a workaround - go to the Checkpoint Merger in the UI.

In the Primary slot, put in the SD1.5 model
In the Secondary slot, put in your safetensors model

Do a weighted sum of 1 by setting the slider all the way to the right and ensure the output is ckpt.

The resulting ckpt file should now allow you to train on the model. I ran a few batches to ensure that the output result was visually the same. 

What's interesting is that putting the safetensors file in the primary slot and creating a ckpt with a WS value of 0 will still give you errors. Even doing a "full overwrite" with a WS value of 1 with the trainable SD1.5 ckpt will still produce errors. 

There appears to be something about putting in a trainable ckpt model in as the Primary value and doing a full copy of the safetensor's values to it that keeps the conversion "clean".

**Comment by d8ahazard** [comment] 2023-01-01 20:16
Closing, duplicate of feature request #625

**Closed by d8ahazard** 2023-01-01 20:16 UTC
Labels: enhancement
