### ISSUE TITLE
[Bug]: train_dreambooth.py", line 1582, in inner_loop not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by FurkanGozukara** [d8ahazard/sd_dreambooth_extension#1358] opened 2023-09-30 13:30 UTC
Here full log

I even did skip install of auto1111 and manually installed

Here config file attached 

[test1.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/12774789/test1.txt)

```
venv "G:\temp 1\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --xformers --skip-install
[2023-09-30 16:26:25,547][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=None)
[2023-09-30 16:26:25,581][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=None)
[2023-09-30 16:26:26,846][DEBUG][api.py] - SD-Webui API layer loaded
Loading weights [31e35c80fc] from G:\temp 1\stable-diffusion-webui\models\Stable-diffusion\sd_xl_base_1.0.safetensors
G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py:301: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
bin G:\temp 1\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
[2023-09-30 16:26:27,670][DEBUG][git.cmd] - Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension, universal_newlines=False, shell=None, istream=None)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: G:\temp 1\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
[2023-09-30 16:26:28,542][INFO][root] - Loaded ViT-bigG-14 model config.
[2023-09-30 16:26:28,548][DEBUG][api.py] - Loading Dreambooth API Endpoints.
Startup time: 7.2s (prepare environment: 1.4s, import torch: 1.8s, import gradio: 0.5s, setup paths: 0.4s, initialize shared: 0.2s, other imports: 0.3s, load scripts: 0.8s, create ui: 0.7s, gradio launch: 0.9s).
[2023-09-30 16:26:30,086][DEBUG][git.cmd] - Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=None)
[2023-09-30 16:26:30,159][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch-check'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=<valid stream>)
[2023-09-30 16:26:30,202][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=<valid stream>)
[2023-09-30 16:26:30,247][DEBUG][git.cmd] - Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=None)
[2023-09-30 16:26:30,295][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch-check'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=<valid stream>)
[2023-09-30 16:26:30,340][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=<valid stream>)
Applying attention optimization: xformers... done.
Model loaded in 6.3s (load weights from disk: 1.3s, create model: 0.3s, apply weights to model: 2.9s, load textual inversion embeddings: 0.8s, calculate empty prompt: 0.8s).
[2023-09-30 16:26:54,662][DEBUG][dreambooth.dataclasses.db_config] - Saving to G:\temp 1\stable-diffusion-webui\models\dreambooth\test1
[2023-09-30 16:26:56,268][DEBUG][dreambooth.dataclasses.db_config] - Saving to G:\temp 1\stable-diffusion-webui\models\dreambooth\test1
Initializing dreambooth training...
[2023-09-30 16:26:56,273][DEBUG][dreambooth.train_dreambooth] - Adding 'get_velocity' method to DEISMultistepScheduler...
[2023-09-30 16:26:56,273][DEBUG][dreambooth.train_dreambooth] - Adding 'get_velocity' method to UniPCMultistepScheduler...
                  [2023-09-30 16:26:56,406][DEBUG][dreambooth.train_dreambooth] - Pretrained path: G:\temp 1\stable-diffusion-webui\models\dreambooth\test1\working/s]
                                                                                                                                                   [2023-09-30 16:26:56,891][INFO][dreambooth.utils.gen_utils] - Nothing to generate.████████████████████       | 3781/4324 [00:00<00:00, 12590.41it/s]
                                                                                                                                                   [2023-09-30 16:26:59,875][DEBUG][dreambooth.utils.gen_utils] - Found 1300 reg images.                                         | 0/5 [00:00<?, ?it/s]
[2023-09-30 16:26:59,876][DEBUG][dreambooth.utils.gen_utils] - Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
                                                                                                                                                   Loading latent cache...h Caching):   0%|                                                                                      | 0/5 [00:00<?, ?it/s]
Bucket 0 (512, 512, 0) - Instance Images: 13 | Class Images: 1300 | Max Examples/batch:   26
                                                                                                                                                   Saving cache!ed latents...: 100%|███████████████████████████████████████████████████████████████████████████████| 1313/1313 [00:38<00:00, 38.12it/s]
[2023-09-30 16:27:38,338][ERROR][dreambooth.dataset.db_dataset] - Error saving cache!
Traceback (most recent call last):
  File "G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dataset\db_dataset.py", line 165, in save_cache_file
    os.remove(cache_file)
PermissionError: [WinError 5] Access is denied: 'G:\\temp 1\\stable-diffusion-webui\\models\\dreambooth\\test1\\cache\\cache_512.safetensors'
Total Buckets 1 - Instance Images: 13 | Class Images: 1300 | Max Examples/batch:   26

Total images / batch: 26, total examples: 26███████████████████████████████████████████████████████████████████| 1313/1313 [00:38<00:00, 38.12it/s]
                                                                                                                                                   [2023-09-30 16:27:38,340][DEBUG][dreambooth.utils.gen_utils] - Total dataset length (steps): 26
                  Initializing bucket counter!
[2023-09-30 16:27:38,484][DEBUG][dreambooth.train_dreambooth] -   ***** Running training *****
[2023-09-30 16:27:38,484][DEBUG][dreambooth.train_dreambooth] -   Num batches each epoch = 26
[2023-09-30 16:27:38,486][DEBUG][dreambooth.train_dreambooth] -   Num Epochs = 100
[2023-09-30 16:27:38,486][DEBUG][dreambooth.train_dreambooth] -   Batch Size Per Device = 1
[2023-09-30 16:27:38,486][DEBUG][dreambooth.train_dreambooth] -   Gradient Accumulation steps = 1
[2023-09-30 16:27:38,487][DEBUG][dreambooth.train_dreambooth] -   Total train batch size (w. parallel, distributed & accumulation) = 1
[2023-09-30 16:27:38,487][DEBUG][dreambooth.train_dreambooth] -   Text Encoder Epochs: 75
[2023-09-30 16:27:38,487][DEBUG][dreambooth.train_dreambooth] -   Total optimization steps = 1300
[2023-09-30 16:27:38,487][DEBUG][dreambooth.train_dreambooth] -   Total training steps = 2600
[2023-09-30 16:27:38,488][DEBUG][dreambooth.train_dreambooth] -   Resuming from checkpoint: False
[2023-09-30 16:27:38,488][DEBUG][dreambooth.train_dreambooth] -   First resume epoch: 0
[2023-09-30 16:27:38,489][DEBUG][dreambooth.train_dreambooth] -   First resume step: 0
[2023-09-30 16:27:38,490][DEBUG][dreambooth.train_dreambooth] -   Lora: False, Optimizer: Lion, Prec: bf16
[2023-09-30 16:27:38,490][DEBUG][dreambooth.train_dreambooth] -   Gradient Checkpointing: False
[2023-09-30 16:27:38,491][DEBUG][dreambooth.train_dreambooth] -   EMA: False
[2023-09-30 16:27:38,492][DEBUG][dreambooth.train_dreambooth] -   UNET: True
[2023-09-30 16:27:38,492][DEBUG][dreambooth.train_dreambooth] -   Freeze CLIP Normalization Layers: False
[2023-09-30 16:27:38,492][DEBUG][dreambooth.train_dreambooth] -   LR: 1e-07
[2023-09-30 16:27:38,493][DEBUG][dreambooth.train_dreambooth] -   Tenc LR: 1e-07
[2023-09-30 16:27:38,493][DEBUG][dreambooth.train_dreambooth] -   V2: False
Steps:   0%|                                                                                                              | 0/2600 [00:00<?, ?it/s]Traceback (most recent call last):
  File "G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 730, in start_training
    result = main(class_gen_method=class_gen_method)
  File "G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1809, in main
    return inner_loop()
  File "G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 126, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1582, in inner_loop
    model_pred, model_pred_prior = torch.chunk(model_pred, 2, dim=0)
ValueError: not enough values to unpack (expected 2, got 1)
Steps:   0%|                                                                                                              | 0/2600 [00:00<?, ?it/s]
Duration: 00:00:44
[2023-09-30 16:27:41,020][DEBUG][dreambooth.utils.model_utils] - Restored system models.
Duration: 00:00:46

```

### Command Line Arguments

```Shell
--xformers --skip-install
```

**Comment by FurkanGozukara** [comment] 2023-09-30 13:38
it gives error in SDXL too

here config file [test2.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/12774791/test2.txt)

```
venv "G:\temp 1\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --xformers --skip-install
[2023-09-30 16:36:17,317][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=None)
[2023-09-30 16:36:17,352][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=None)
[2023-09-30 16:36:18,839][DEBUG][api.py] - SD-Webui API layer loaded
Loading weights [31e35c80fc] from G:\temp 1\stable-diffusion-webui\models\Stable-diffusion\sd_xl_base_1.0.safetensors
G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py:301: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
bin G:\temp 1\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: G:\temp 1\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
[2023-09-30 16:36:20,465][INFO][root] - Loaded ViT-bigG-14 model config.
[2023-09-30 16:36:20,501][DEBUG][api.py] - Loading Dreambooth API Endpoints.
Startup time: 8.4s (prepare environment: 1.8s, import torch: 2.2s, import gradio: 0.7s, setup paths: 0.6s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 0.9s, create ui: 0.8s, gradio launch: 0.6s).
[2023-09-30 16:36:22,540][DEBUG][git.cmd] - Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=None)
[2023-09-30 16:36:22,583][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch-check'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=<valid stream>)
[2023-09-30 16:36:22,624][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=<valid stream>)
[2023-09-30 16:36:22,664][DEBUG][git.cmd] - Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=None)
[2023-09-30 16:36:22,708][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch-check'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=<valid stream>)
[2023-09-30 16:36:22,755][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch'], cwd=G:\temp 1\stable-diffusion-webui, universal_newlines=False, shell=None, istream=<valid stream>)
[2023-09-30 16:36:28,115][DEBUG][dreambooth.dataclasses.db_config] - Saving to G:\temp 1\stable-diffusion-webui\models\dreambooth\test2
Applying attention optimization: xformers... done.
Model loaded in 10.9s (load weights from disk: 1.2s, create model: 0.3s, apply weights to model: 7.4s, move model to device: 0.1s, load textual inversion embeddings: 0.9s, calculate empty prompt: 0.8s).
[2023-09-30 16:36:32,144][DEBUG][dreambooth.dataclasses.db_config] - Saving to G:\temp 1\stable-diffusion-webui\models\dreambooth\test2
Initializing dreambooth training...
[2023-09-30 16:36:32,150][DEBUG][dreambooth.train_dreambooth] - Adding 'get_velocity' method to DEISMultistepScheduler...
[2023-09-30 16:36:32,150][DEBUG][dreambooth.train_dreambooth] - Adding 'get_velocity' method to UniPCMultistepScheduler...
                  [2023-09-30 16:36:32,306][DEBUG][dreambooth.train_dreambooth] - Pretrained path: G:\temp 1\stable-diffusion-webui\models\dreambooth\test2\working/s]
                                                                                                                                                   [2023-09-30 16:36:34,936][INFO][dreambooth.utils.gen_utils] - Nothing to generate.███████████████████████████ | 4250/4324 [00:02<00:00, 1802.44it/s]
                                                                                                                                                   [2023-09-30 16:36:49,836][DEBUG][dreambooth.utils.gen_utils] - Found 130 reg images.                                          | 0/7 [00:00<?, ?it/s]
[2023-09-30 16:36:49,836][DEBUG][dreambooth.utils.gen_utils] - Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
                                                                                                                                                   Loading latent cache...h Caching):   0%|                                                                                      | 0/7 [00:00<?, ?it/s]
Bucket 0 (1024, 1024, 0) - Instance Images: 13 | Class Images: 130 | Max Examples/batch:  26
                                                                                                                                                   Saving cache!ed latents...: 100%|█████████████████████████████████████████████████████████████████████████████████| 143/143 [00:56<00:00,  2.32it/s]
[2023-09-30 16:37:46,119][ERROR][dreambooth.dataset.db_dataset] - Error saving cache!
Traceback (most recent call last):
  File "G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dataset\db_dataset.py", line 165, in save_cache_file
    os.remove(cache_file)
PermissionError: [WinError 5] Access is denied: 'G:\\temp 1\\stable-diffusion-webui\\models\\dreambooth\\test2\\cache\\cache_1024.safetensors'
Total Buckets 1 - Instance Images: 13 | Class Images: 130 | Max Examples/batch:  26

Total images / batch: 26, total examples: 26█████████████████████████████████████████████████████████████████████| 143/143 [00:56<00:00,  2.32it/s]
                                                                                                                                                   [2023-09-30 16:37:46,123][DEBUG][dreambooth.utils.gen_utils] - Total dataset length (steps): 26
                  Initializing bucket counter!
[2023-09-30 16:37:46,244][DEBUG][dreambooth.train_dreambooth] -   ***** Running training *****
[2023-09-30 16:37:46,244][DEBUG][dreambooth.train_dreambooth] -   Num batches each epoch = 26
[2023-09-30 16:37:46,245][DEBUG][dreambooth.train_dreambooth] -   Num Epochs = 100
[2023-09-30 16:37:46,246][DEBUG][dreambooth.train_dreambooth] -   Batch Size Per Device = 1
[2023-09-30 16:37:46,246][DEBUG][dreambooth.train_dreambooth] -   Gradient Accumulation steps = 1
[2023-09-30 16:37:46,246][DEBUG][dreambooth.train_dreambooth] -   Total train batch size (w. parallel, distributed & accumulation) = 1
[2023-09-30 16:37:46,247][DEBUG][dreambooth.train_dreambooth] -   Text Encoder Epochs: 75
[2023-09-30 16:37:46,248][DEBUG][dreambooth.train_dreambooth] -   Total optimization steps = 1300
[2023-09-30 16:37:46,248][DEBUG][dreambooth.train_dreambooth] -   Total training steps = 2600
[2023-09-30 16:37:46,248][DEBUG][dreambooth.train_dreambooth] -   Resuming from checkpoint: False
[2023-09-30 16:37:46,249][DEBUG][dreambooth.train_dreambooth] -   First resume epoch: 0
[2023-09-30 16:37:46,249][DEBUG][dreambooth.train_dreambooth] -   First resume step: 0
[2023-09-30 16:37:46,249][DEBUG][dreambooth.train_dreambooth] -   Lora: False, Optimizer: Lion, Prec: bf16
[2023-09-30 16:37:46,249][DEBUG][dreambooth.train_dreambooth] -   Gradient Checkpointing: False
[2023-09-30 16:37:46,249][DEBUG][dreambooth.train_dreambooth] -   EMA: False
[2023-09-30 16:37:46,250][DEBUG][dreambooth.train_dreambooth] -   UNET: True
[2023-09-30 16:37:46,250][DEBUG][dreambooth.train_dreambooth] -   Freeze CLIP Normalization Layers: False
[2023-09-30 16:37:46,250][DEBUG][dreambooth.train_dreambooth] -   LR: 1e-05
[2023-09-30 16:37:46,250][DEBUG][dreambooth.train_dreambooth] -   Tenc LR: 1e-05
[2023-09-30 16:37:46,250][DEBUG][dreambooth.train_dreambooth] -   V2: False
Steps:   0%|                                                                                                              | 0/2600 [00:00<?, ?it/s]Traceback (most recent call last):
  File "G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 730, in start_training
    result = main(class_gen_method=class_gen_method)
  File "G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1809, in main
    return inner_loop()
  File "G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 126, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "G:\temp 1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1597, in inner_loop
    model_pred, model_pred_prior = torch.chunk(model_pred, 2, dim=0)
ValueError: not enough values to unpack (expected 2, got 1)
Steps:   0%|                                                                                                              | 0/2600 [00:00<?, ?it/s]
Duration: 00:01:19
[2023-09-30 16:37:49,135][DEBUG][dreambooth.utils.model_utils] - Restored system models.
Duration: 00:01:21
```

**Comment by FurkanGozukara** [comment] 2023-09-30 13:39
here the venv pip freeze

```
Microsoft Windows [Version 10.0.19045.3448]
(c) Microsoft Corporation. All rights reserved.

G:\temp 1\stable-diffusion-webui\venv\Scripts>activate

(venv) G:\temp 1\stable-diffusion-webui\venv\Scripts>pip freeze
absl-py==2.0.0
accelerate==0.23.0
addict==2.4.0
aenum==3.1.15
aiofiles==23.2.1
aiohttp==3.8.5
aiosignal==1.3.1
altair==5.1.1
antlr4-python3-runtime==4.9.3
anyio==3.7.1
async-timeout==4.0.3
attrs==23.1.0
basicsr==1.4.2
beautifulsoup4==4.12.2
bitsandbytes @ https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl
blendmodes==2022
boltons==23.0.0
cachetools==5.3.1
certifi==2023.7.22
charset-normalizer==3.3.0
clean-fid==0.1.35
click==8.1.7
clip==1.0
colorama==0.4.6
contourpy==1.1.1
cycler==0.12.0
dadaptation==3.1
deprecation==2.1.0
diffusers==0.21.4
discord-webhook==1.1.0
einops==0.4.1
exceptiongroup==1.1.3
facexlib==0.3.0
fastapi==0.94.1
ffmpy==0.3.1
filelock==3.12.4
filterpy==1.4.5
fonttools==4.43.0
frozenlist==1.4.0
fsspec==2023.9.2
ftfy==6.1.1
future==0.18.3
gdown==4.7.1
gfpgan==1.3.8
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.23.2
google-auth-oauthlib==1.0.0
gradio==3.41.2
gradio_client==0.5.0
grpcio==1.59.0
h11==0.12.0
httpcore==0.15.0
httpx==0.24.1
huggingface-hub==0.17.3
idna==3.4
imageio==2.31.4
importlib-metadata==6.8.0
importlib-resources==6.1.0
inflection==0.5.1
Jinja2==3.1.2
jsonmerge==1.8.0
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
kiwisolver==1.4.5
kornia==0.6.7
lark==1.1.2
lazy_loader==0.3
lightning-utilities==0.9.0
llvmlite==0.41.0
lmdb==1.4.1
lpips==0.1.4
Markdown==3.4.4
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
multidict==6.0.4
networkx==3.1
numba==0.58.0
numpy==1.23.5
oauthlib==3.2.2
omegaconf==2.2.3
open-clip-torch==2.20.0
opencv-python==4.8.1.78
orjson==3.9.7
packaging==23.1
pandas==2.1.1
piexif==1.1.3
Pillow==9.5.0
platformdirs==3.10.0
protobuf==3.20.0
psutil==5.9.5
pyasn1==0.5.0
pyasn1-modules==0.3.0
pydantic==1.10.13
pydub==0.25.1
pyparsing==3.1.1
PySocks==1.7.1
python-dateutil==2.8.2
python-multipart==0.0.6
pytorch-lightning==1.9.4
pytorch-optimizer==2.11.1
pytz==2023.3.post1
PyWavelets==1.4.1
PyYAML==6.0.1
realesrgan==0.3.0
referencing==0.30.2
regex==2023.8.8
requests==2.31.0
requests-oauthlib==1.3.1
resize-right==0.0.2
rpds-py==0.10.3
rsa==4.9
safetensors==0.3.1
scikit-image==0.21.0
scipy==1.11.3
semantic-version==2.10.0
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
soupsieve==2.5
starlette==0.26.1
sympy==1.12
tb-nightly==2.15.0a20230930
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tifffile==2023.9.26
timm==0.9.2
tokenizers==0.13.3
tomesd==0.1.3
tomli==2.0.1
toolz==0.12.0
torch==2.0.1+cu118
torchdiffeq==0.2.3
torchmetrics==1.2.0
torchsde==0.2.5
torchvision==0.15.2+cu118
tqdm==4.65.0
trampoline==0.1.2
transformers==4.30.2
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.0.5
uvicorn==0.23.2
wcwidth==0.2.8
websockets==11.0.3
Werkzeug==2.3.7
xformers==0.0.20
yapf==0.40.2
yarl==1.9.2
zipp==3.17.0

(venv) G:\temp 1\stable-diffusion-webui\venv\Scripts>
```

**Comment by FurkanGozukara** [comment] 2023-09-30 13:39
@d8ahazard @saunderez 

i attached all confings and pip freeze

**Comment by FurkanGozukara** [comment] 2023-09-30 23:47
@d8ahazard @saunderez 

I found the error

This error happens when classification images are used

When it is disabled it is working

![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/19240467/a518c442-1356-4018-ae54-3dd7e1c2afc7)


after I make it 0

![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/19240467/6956dd17-c28f-40f0-8fb2-1226d99f3160)


it starts working

![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/19240467/3791dd13-1201-4df2-8182-c9ec1075aa8d)

**Comment by FurkanGozukara** [comment] 2023-10-01 00:00
this time i have error during saving

Exception training model: ''AttnProcessor2_0' object has no attribute 'state_dict''.

**Comment by FurkanGozukara** [comment] 2023-10-01 00:12
![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/19240467/0088261b-8af5-4e84-ac9a-28e59b95eeb4)

![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/19240467/497218d2-bb1e-44aa-a797-da1147c6b8ed)

**Comment by munishm** [comment] 2023-10-03 12:08
+1 getting the same error

**Comment by unixunion** [comment] 2023-10-08 17:21
Any workaround with this? roll back to a tag of dreambooth or a specific python module version?

**Comment by yhsharaf** [comment] 2023-10-08 19:45
> Any workaround with this? roll back to a tag of dreambooth or a specific python module version?

Reverting back to this Hash solved the issue: fce70444183fa68906a5f49b3591c1ded2d55f77
for me

**Comment by FurkanGozukara** [comment] 2023-10-08 22:11
i made an auto installer that installs specific version of auto1111 and dreambooth as in my last best video

that works perfect but no sdxl

https://www.patreon.com/posts/auto-installer-84773926

**Comment by Chris611** [comment] 2023-10-09 10:19
I also had this bug (together with issues/1363).   Linux Mint 21 (Ubuntu 22.04)

Went back a bunch of commits, to July, with xformers 0.0.17, torch 2.0.0+cu117 and torchvision 0.15.1+cu117.  Then it works.

**Comment by hughc** [comment] 2023-10-09 11:13
> Reverting back to this sd_dreambooth_extension Hash solved the issue: [fce7044](https://github.com/d8ahazard/sd_dreambooth_extension/commit/fce70444183fa68906a5f49b3591c1ded2d55f77) for me

Thanks for this, did the trick for me. If anyone else wants to try this version rollback, go to the `extensions/sd_dreambooth_extension` directory and execute

`git reset --hard fce70444183fa68906a5f49b3591c1ded2d55f77`

I'm running Python 3.10, CUDA 11.8 ; originally had xformers 0.022 installed, rolled that back to 0.021, but made no difference. 

After rolling back I had a couple of crashes when training running with xformers enabled, but was able to train my first model by omitting the startup flag.

**Comment by aryan1107** [comment] 2023-10-26 18:26
Same error

**Comment by swumagic** [comment] 2023-11-10 06:06
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment] 2023-11-12 02:03
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by d8ahazard** [comment] 2023-11-16 02:48
Closed, dupe of #1371 #1360 #1369, fixed.

**Closed by d8ahazard** 2023-11-16 02:48 UTC

**Comment by claytonmark** [comment] 2023-12-10 23:32
I have a good install (no CUDA errors, no library problems) and I'm still getting this.  Seems to be an issue with using SDXL+Class Images.

**Comment by fawolfmann** [comment] 2023-12-13 14:43
Same error here, SDXL+Class Images with Lora,  works when turning of class images. 
torch 2.0.1, bitsandbytes 0.41.3.post1, CUDA Version: 12.2 on a NVIDIA A10.
