### ISSUE TITLE
 loaded_state_dict_keys = [k for k in state_dict.keys()] AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by hulululu7654321** [d8ahazard/sd_dreambooth_extension#82] opened 2022-11-10 00:14 UTC
Error completing request
Arguments: ('123', '123', '', 'sakichiman', 'sakichiman style', '', '', 1.0, 7.5, 40.0, 0, 512, False, True, 1, 1, 1, 1000, 1, True, 5e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 500, 500, 'no', True, '', False, True, True) {}
Traceback (most recent call last):
  File "/home/hulululu/desktop/stable-diffusion-webui-master/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/home/hulululu/desktop/stable-diffusion-webui-master/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/home/hulululu/desktop/stable-diffusion-webui-master/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "/home/hulululu/desktop/stable-diffusion-webui-master/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 602, in main
    text_encoder = CLIPTextModel.from_pretrained(os.path.join(args.working_dir, "text_encoder"))
  File "/home/hulululu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2006, in from_pretrained
    loaded_state_dict_keys = [k for k in state_dict.keys()]
AttributeError: 'NoneType' object has no attribute 'keys'

Dreambooth revision is 08394f983153175685658a3d49249915212d40fc
Diffusers version is 0.7.2
Torch version is 1.12.0+rocm5.1.1.
Torch vision version is 0.13.0+cu116.

**Describe the bug**
AttributeError occurs

**Provide logs**
    loaded_state_dict_keys = [k for k in state_dict.keys()]
AttributeError: 'NoneType' object has no attribute 'keys'

**Environment**
Ubuntu
AMD 6800XT (gfx1030 with Rocms version torch)

**Comment by d8ahazard** [comment] 2022-11-10 17:03
Closing, duplicate of #9

**Closed by d8ahazard** 2022-11-10 17:03 UTC
