### ISSUE TITLE
Add multiple aspect ratio support

### ISSUE THREAD

**Issue by zakinp** [d8ahazard/sd_dreambooth_extension#332] opened 2022-11-26 17:40 UTC
The multiple aspect ratio images training support has been released by NovelAI. Can you merge it into the dreambooth extension ? It'll be amazing.

https://github.com/NovelAI/novelai-aspect-ratio-bucketing

**Comment by d8ahazard** [comment] 2022-11-26 19:24
This is a duplicate of #176, and is next up on the list of features to try incorporating.

**Closed by d8ahazard** 2022-11-26 19:24 UTC
